#!/bin/bash
# Universe Grok - UserPromptSubmit Research Forcer
#
# This hook runs on every user prompt submission.
# It creates a per-turn research request artifact and injects a mandatory
# instruction via additionalContext so the agent MUST do fresh web_search + x_search
# as its very first action for this specific prompt.
#
# This is the fundamental (non-overfitting) mechanism for per-message external research.
# The user controls query formulation logic inside this script later.

set -euo pipefail

echo "[Universe Grok] UserPromptSubmit hook executing..." >&2

WORKSPACE="${GROK_WORKSPACE_ROOT:-$(pwd)}"

# Read the full event from stdin (JSON)
INPUT=$(cat)

# Extract the actual user prompt
USER_PROMPT=$(echo "$INPUT" | jq -r '.prompt // empty' 2>/dev/null || echo "")

if [ -z "$USER_PROMPT" ]; then
  echo "[Universe Grok] No prompt found in UserPromptSubmit event, skipping research request." >&2
  exit 0
fi

# Create research directory
RESEARCH_DIR="$WORKSPACE/.grok/research"
mkdir -p "$RESEARCH_DIR"

RESEARCH_FILE="$RESEARCH_DIR/current-prompt-research-request.md"

# Write a clean, actionable research request artifact for this exact prompt
cat > "$RESEARCH_FILE" << EOF
# Current User Prompt - Fresh External Research Request

**Generated by**: UserPromptSubmit hook at $(date -u +"%Y-%m-%dT%H:%M:%SZ")
**Workspace**: $WORKSPACE

## Original User Prompt
$USER_PROMPT

## Instruction to Agent (Mandatory for this turn)
For the exact user prompt above, you **must** perform fresh external research using Grok's built-in tools **before any other reasoning or response**.

1. Execute web_search (for authoritative sources, current docs, best practices)
2. Execute x_search (for recent high-signal practitioner signals on X, 2025-2026)

Use the content of this file to formulate good search queries. Prioritize recency and real-world usage.

Only after you have received and processed the fresh results should you proceed to analyze the user's request and formulate an answer.

This request exists because the user submitted a new prompt. It takes precedence for the current turn.
EOF

echo "[Universe Grok] Research request artifact written to: $RESEARCH_FILE" >&2

# This is the key part: we inject a short, high-signal instruction directly into the agent's
# context for *this turn* using the official UserPromptSubmit additionalContext mechanism.
# This is "prompt modification via hook" — the fundamental lever the user asked for.

cat << 'JSONEOF'
{
  "hookSpecificOutput": {
    "hookEventName": "UserPromptSubmit",
    "additionalContext": "**MANDATORY FIRST ACTION FOR THIS PROMPT**: A research request for the exact prompt you just received has been written to .grok/research/current-prompt-research-request.md. Your absolute first actions this turn must be to read that file and immediately execute parallel web_search + x_search based on its content. Do not begin substantive reasoning, planning, or answering until you have incorporated fresh external results."
  }
}
JSONEOF

echo "[Universe Grok] UserPromptSubmit hook completed. additionalContext injected." >&2

exit 0